[package]
name = "BNS"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
reqwest = { version = "0.12.15", features = ["blocking"] }
serde = { version = "*", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
url = "2.5.4"
